// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Conquistas
{
        public const string achievement_execuo_quaternria = "CgkIgPT5l8oJEAIQEA"; // <GPGSID>
        public const string achievement_cofres_pblicos = "CgkIgPT5l8oJEAIQBQ"; // <GPGSID>
        public const string achievement_ado_e_eva = "CgkIgPT5l8oJEAIQCw"; // <GPGSID>
        public const string achievement_execuo_terciria = "CgkIgPT5l8oJEAIQCA"; // <GPGSID>
        public const string achievement_execuo_secundria = "CgkIgPT5l8oJEAIQBw"; // <GPGSID>
        public const string achievement_abaixo_de_zero = "CgkIgPT5l8oJEAIQAg"; // <GPGSID>
        public const string achievement_velho_tanque = "CgkIgPT5l8oJEAIQCg"; // <GPGSID>
        public const string achievement_jeitinho_brasileiro = "CgkIgPT5l8oJEAIQAA"; // <GPGSID>
        public const string achievement_sobrevivente_catico = "CgkIgPT5l8oJEAIQDQ"; // <GPGSID>
        public const string achievement_pequena_mquina_de_combate = "CgkIgPT5l8oJEAIQCQ"; // <GPGSID>
        public const string achievement_presente_de_grego = "CgkIgPT5l8oJEAIQAQ"; // <GPGSID>
        public const string leaderboard_ranking_geral = "CgkIgPT5l8oJEAIQDw"; // <GPGSID>
        public const string achievement_execuo_primria = "CgkIgPT5l8oJEAIQAw"; // <GPGSID>
        public const string achievement_cofres_privados = "CgkIgPT5l8oJEAIQBg"; // <GPGSID>
        public const string achievement_soldado_iniciante = "CgkIgPT5l8oJEAIQBA"; // <GPGSID>
        public const string achievement_fuso_horrio = "CgkIgPT5l8oJEAIQDA"; // <GPGSID>

}

